# Generated by Django 2.0.7 on 2019-02-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='', max_length=280),
        ),
    ]
