# Generated by Django 2.0.7 on 2019-02-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('summary', models.TextField(max_length=128)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(default='', max_length=280, unique=True),
        ),
    ]
