# Generated by Django 2.0.7 on 2019-02-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190208_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('summary', models.TextField(max_length=128)),
                ('content', models.TextField()),
                ('url', models.URLField(default='', max_length=280, unique=True)),
                ('thumbnail', models.ImageField(default='https://miro.medium.com/max/800/1*bNfxs62uJzISTfuPlOzOWQ.png', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='https://i.pinimg.com/236x/1c/92/b6/1c92b62cf9d3430cab6d1b3bd9158665--sports-logos-soccer-ball.jpg', upload_to=''),
        ),
    ]
