# Generated by Django 2.0.7 on 2019-02-12 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190212_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 12, 7, 17, 41, 164727)),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='https://cdn3.iconfinder.com/data/icons/tech-icons/64/Computer_Chip-512.png', upload_to=''),
        ),
    ]
